---
- hosts: gitlab_server
  become: true
  roles:
    - role: gitlab/install
      tags: install

    - role: gitlab/healthchecks
      tags: [check, readiness, liveness] # Ajout de readiness et liveness aux tags
