version: '3'
services:
  redis:
    image: redis
    volumes:
      - redis-data:/data
  web:
    image: my-docker-app
    ports:
      - "5000:8080"
    environment:
      REDIS_HOST: redis

volumes:
  redis-data:
